def tables_to_transfer():

  # === GROUP 1: Core System, Users & Roles (Transfer FIRST) ===
  # These tables define the fundamental users, contexts, and permissions.
  core_and_user_tables = [
      "config",
      "config_log",
      "config_plugins",
      "context",
      "user",
      "user_info_category",
      "user_info_data",
      "user_info_field",
      "user_lastaccess",
      "user_preferences",
      "user_private_key",
      "role",
      "role_assignments",
      "role_context_levels",
      "role_names",
      "role_sortorder",
      "role_allow_assign",
      "role_allow_override",
      "role_allow_switch",
      "cohort",
      "cohort_members",
  ]

  # === GROUP 2: Course Structure & Enrolment (Transfer SECOND) ===
  # These tables define the courses and how users are enrolled in them.
  course_and_enrolment_tables = [
      "course_categories",
      "course",
      "course_sections",
      "course_modules",
      "course_modules_completion",
      "course_completions",
      "course_completion_criteria",
      "course_completion_crit_compl",
      "enrol",
      "user_enrolments",
      "enrol_flatfile", # if you use it
      "enrol_guest",    # if you use it
      "enrol_ldap",     # if you use it
      "enrol_manual",   # if you use it
      "enrol_self",     # if you use it
      # Add other enrol_ plugin tables if you use them
      "groups",
      "groups_members",
      "groupings",
      "groupings_groups",
  ]

  # === GROUP 3: Core Content & Activity Modules (Transfer THIRD) ===
  # This is the largest group, containing the actual learning content.
  # The order within this group is less critical, but transfer them all.
  activity_and_content_tables = [
      # Core Content
      "files",
      "files_reference",
      "filter_active",
      "filter_config",
      "question_categories",
      "question",
      "Youtubes",
      "question_attempt_steps",
      "question_attempt_step_data",
      "question_attempts",
      "question_calculated",
      "question_dataset_definitions",
      "question_dataset_items",
      "question_datasets",
      "question_ddwtos",
      "question_gapselect",
      "question_match",
      "question_match_sub",
      "question_multianswer",
      "question_multichoice",
      "question_numerical",
      "question_numerical_options",
      "question_numerical_units",
      "question_randomsamatch",
      "question_shortanswer",
      "question_truefalse",
      "question_essay",
      "question_usage",
      "question_statistics",
      "question_response_analysis",
      "question_response_count",
      "tag",
      "tag_instance",
      "tag_correlation",
      # Standard Modules (you may have more for custom plugins)
      "assign",
      "assign_grades",
      "assign_plugin_config",
      "assign_submission",
      "assign_user_flags",
      "assign_user_mapping",
      "assignment", # Legacy, but might have data
      "assignment_submissions", # Legacy
      "book",
      "book_chapters",
      "chat",
      "chat_messages",
      "chat_messages_current",
      "chat_users",
      "choice",
      "choice_answers",
      "data",
      "data_content",
      "data_fields",
      "data_records",
      "feedback",
      "feedback_completed",
      "feedback_completedtmp",
      "feedback_item",
      "feedback_sitecourse_map",
      "feedback_template",
      "feedback_value",
      "feedback_valuetmp",
      "folder",
      "forum",
      "forum_digests",
      "forum_discussions",
      "forum_posts",
      "forum_queue",
      "forum_read",
      "forum_subscriptions",
      "forum_track_prefs",
      "glossary",
      "glossary_categories",
      "glossary_entries",
      "glossary_entries_categories",
      "glossary_formats",
      "h5p",
      "h5p_contents_libraries",
      "h5p_libraries",
      "h5p_libraries_cachedassets",
      "h5p_library_dependencies",
      "h5pactivity",
      "h5pactivity_attempts",
      "h5pactivity_attempts_results",
      "imscp",
      "label",
      "lesson",
      "lesson_answers",
      "lesson_attempts",
      "lesson_branch",
      "lesson_grades",
      "lesson_overrides",
      "lesson_pages",
      "lesson_timer",
      "lti",
      "lti_access_tokens",
      "lti_tool_proxies",
      "lti_tool_settings",
      "lti_types",
      "lti_types_config",
      "page",
      "quiz",
      "quiz_attempts",
      "quiz_feedback",
      "quiz_grades",
      "quiz_overrides",
      "quiz_reports",
      "quiz_sections",
      "quiz_slot_tags",
      "quiz_slots",
      "quiz_statistics",
      "resource",
      "scorm",
      "scorm_scoes",
      "scorm_scoes_track",
      "scorm_seq_mapinfo",
      "scorm_seq_objective",
      "scorm_seq_rolluprule",
      "scorm_seq_rolluprulecond",
      "scorm_seq_rulecond",
      "scorm_seq_ruleconds",
      "survey",
      "survey_analysis",
      "survey_answers",
      "survey_questions",
      "url",
      "wiki",
      "wiki_links",
      "wiki_locks",
      "wiki_pages",
      "wiki_subwikis",
      "wiki_versions",
      "workshop",
      "workshop_aggregations",
      "workshop_assessments",
      "workshop_grades",
      "workshop_submissions",
  ]

  # === GROUP 4: Grades, Logs, and Miscellaneous (Transfer FOURTH) ===
  # Data related to grading, system logs, and other functionality.
  grading_and_logs_tables = [
      "grade_categories",
      "grade_categories_history",
      "grade_grades",
      "grade_grades_history",
      "grade_import_newitem",
      "grade_import_values",
      "grade_items",
      "grade_items_history",
      "grade_letters",
      "grade_outcomes",
      "grade_outcomes_courses",
      "grade_outcomes_history",
      "grade_settings",
      "grading_areas",
      "grading_definitions",
      "grading_instances",
      "gradingform_guide_comments",
      "gradingform_guide_criteria",
      "gradingform_guide_fillings",
      "gradingform_rubric_criteria",
      "gradingform_rubric_fillings",
      "gradingform_rubric_levels",
      "logstore_standard_log", # This can be a very large table!
      "log", # Legacy log table
      "event",
      "event_subscriptions",
      "message",
      "message_airnotifier_devices",
      "message_contacts",
      "message_conversation_members",
      "message_conversations",
      "message_popup",
      "message_popup_notifications",
      "message_processors",
      "message_providers",
      "message_read",
      "message_user_actions",
      "message_users_blocked",
      "my_pages",
      "notifications",
      "post", # For comments
      "rating",
      "context_temp",
      "external_services",
      "external_services_functions",
      "external_services_users",
      "external_tokens",
      "files_trash",
      "tool_customlang",
      "tool_customlang_components",
      "tool_dataprivacy_category",
      "tool_dataprivacy_ctxexpired",
      "tool_dataprivacy_ctxinstance",
      "tool_dataprivacy_purpose",
      "tool_dataprivacy_purposerole",
      "tool_dataprivacy_request",
      "tool_monitor_events",
      "tool_monitor_history",
      "tool_monitor_rules",
      "tool_monitor_subscriptions",
      "tool_usertours_steps",
      "tool_usertours_tours",
      "upgrade_log",
  ]

  # === GROUP 5: Caches, Sessions, and Locks (DO NOT TRANSFER) ===
  # These are temporary and will be rebuilt by the new system.
  # Transferring them can cause serious issues.
  # Example tables: cache_*, sessions, lock_*
  # It's safer to just not transfer them.

  # Combine all the tables you want to transfer into one master list
  all_tables_to_transfer = (
      core_and_user_tables +
      course_and_enrolment_tables +
      activity_and_content_tables +
      grading_and_logs_tables
  )
  return all_tables_to_transfer
