def tables_to_transfer():
    return [
        # === Core Config & Users ===
        "config",
        "config_plugins",
        "config_log",
        "context",
        "user",
        "user_info_category",
        "user_info_field",
        "user_info_data",
        "user_preferences",
        "user_private_key",
        "user_lastaccess",
        "role",
        "role_assignments",
        "role_context_levels",
        "role_allow_assign",
        "role_allow_override",
        "role_allow_switch",

        # === Courses & Enrolment ===
        "course_categories",
        "course",
        "course_sections",
        "course_modules",
        "course_modules_completion",
        "course_completion_criteria",
        "course_completion_crit_compl",
        "course_completions",
        "enrol",
        "user_enrolments",
        "cohort",
        "cohort_members",
        "groups",
        "groups_members",
        "groupings",
        "groupings_groups",

        # === Assignments ===
        "assign",
        "assign_grades",
        "assign_plugin_config",
        "assign_submission",
        "assign_user_flags",
        "assign_user_mapping",
        "assignfeedback_comments",
        "assignfeedback_editpdf_annot",
        "assignfeedback_editpdf_cmnt",
        "assignfeedback_editpdf_queue",
        "assignfeedback_editpdf_quick",
        "assignfeedback_file",
        "assignsubmission_file",
        "assignsubmission_onlinetext",
        "assignment",  # legacy
        "assignment_submissions",  # legacy

        # === Attendance Plugin ===
        "attendance",
        "attendance_log",
        "attendance_sessions",
        "attendance_statuses",
        "attendance_warning",
        "attendance_warning_done",

        # === Quizzes & Questions ===
        "quiz",
        "quiz_attempts",
        "quiz_feedback",
        "quiz_grades",
        "quiz_overrides",
        "quiz_slots",
        "quiz_statistics",
        "question_categories",
        "question",
        "question_attempt_steps",
        "question_attempt_step_data",
        "question_attempts",
        "question_answers",
        "question_calculated",
        "question_ddwtos",
        "question_gapselect",
        "question_truefalse",
        "question_numerical",
        "question_multichoice",
        "question_multianswer",
        "question_shortanswer",

        # === Forums ===
        "forum",
        "forum_discussions",
        "forum_posts",
        "forum_read",
        "forum_subscriptions",

        # === Other Activities ===
        "book",
        "book_chapters",
        "chat",
        "chat_messages",
        "chat_users",
        "choice",
        "choice_answers",
        "data",
        "data_fields",
        "data_records",
        "data_content",
        "feedback",
        "feedback_completed",
        "feedback_item",
        "feedback_value",
        "folder",
        "glossary",
        "glossary_entries",
        "lesson",
        "lesson_pages",
        "lesson_attempts",
        "page",
        "resource",
        "scorm",
        "scorm_scoes",
        "scorm_scoes_track",
        "survey",
        "survey_questions",
        "survey_answers",
        "url",
        "wiki",
        "wiki_pages",
        "wiki_versions",
        "workshop",
        "workshop_submissions",
        "workshop_assessments",

        # === H5P / Interactive Content ===
        "h5p",
        "h5pactivity",
        "h5pactivity_attempts",
        "h5pactivity_attempts_results",
        "hvp",  # if old plugin used
        "hvp_contents_libraries",
        "hvp_libraries",
        "hvp_xapi_results",

        # === Tags, Logs, Feedback ===
        "tag",
        "tag_instance",
        "grade_items",
        "grade_grades",
        "grade_categories",

        # === Messaging ===
        "message",
        "message_conversations",
        "message_conversation_members",
        "message_popup",
        "message_read",

        # === Analytics & Monitoring (if used) ===
        "analytics_models",
        "analytics_predictions",
        #"logstore_standard_log",
        "event",
    ]
